apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: central-catalog
  description: Central catalog referencing multiple services
spec:
  type: url
  targets:
    - https://github.com/raunakkhatri/python-app/blob/main/service-a/catalog-info.yaml
    - https://github.com/raunakkhatri/python-app/blob/main/service-b/catalog-info.yaml
