# apiVersion: backstage.io/v1alpha1
# kind: Domain
# metadata:
#   name: data-processing
#   description: Domain for data-processing services.
# spec:
#   owner: group:developer
# ---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: python-app-prod
  description: Python application production environment.
spec:
  owner: group:developer
  domain: data-processing
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: python-app-prod-api
  description: API definition for Python App Production.
spec:
  type: openapi
  lifecycle: production
  owner: group:developer
  definition:
    $text: ./openapi.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: python-app-prod-db-us
  description: Production database - US region.
spec:
  type: database
  system: python-app-prod
  owner: group:developer
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: python-app-prod-db-eu
  description: Production database - EU region.
spec:
  type: database
  system: python-app-prod
  owner: group:developer
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: python-app-prod-db-asia
  description: Production database - Asia region.
spec:
  type: database
  system: python-app-prod
  owner: group:developer
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app-prod-service
  description: Python application service for production environment across multiple regions.

  annotations:
    backstage.io/kubernetes-label-selector: app=python-app-prod
    backstage.io/techdocs-ref: dir:./docs
    
    argocd/app-name: python-app-prod
    argocd/instance-name: default

spec:
  type: service
  lifecycle: production
  owner: group:developer
  system: python-app-prod

  providesApis:
    - api:default/python-app-prod-api

  dependsOn:
    - resource:default/python-app-prod-db-us
    - resource:default/python-app-prod-db-eu
    - resource:default/python-app-prod-db-asia
