# apiVersion: backstage.io/v1alpha1
# kind: Domain
# metadata:
#   name: data-processing
#   description: Domain for data-processing services.
# spec:
#   owner: group:developer
# ---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: service-a
  description: data-processing microservices running across multiple environments.
spec:
  owner: group:developer
  domain: data-processing
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: serviceA-api
  description: API definition for the serviceA Service.
spec:
  type: openapi
  lifecycle: production
  owner: group:developer
  definition:
    $text: ./openapi.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: serviceA-db-us
  description: Simulated DB for US environment.
spec:
  type: database
  system: service-a
  owner: group:developer
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: serviceA-db-eu
  description: Simulated DB for EU environment.
spec:
  type: database
  system: service-a
  owner: group:developer
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: serviceA-db-asia
  description: Simulated DB for Asia environment.
spec:
  type: database
  system: service-a
  owner: group:developer
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: serviceA-service
  description: >
    serviceA service deployed locally in multiple namespaces 
    (us-prod, eu-dev, asia-qa) with different versions.

  annotations:
    # Matches all your deployed services:
    backstage.io/kubernetes-label-selector: app=serviceA-service

    backstage.io/techdocs-ref: dir:./docs

spec:
  type: service
  lifecycle: production
  owner: group:developer
  system: service-a

  providesApis:
    - api:default/serviceA-api

  dependsOn:
    - resource:default/serviceA-db-us
    - resource:default/serviceA-db-eu
    - resource:default/serviceA-db-asia
